### ISSUE TITLE
Empty event on PauseSnapping in Locomotors.Teleporter.Instant prefab

### ISSUE THREAD

**Issue by Maciej92Zareba** [ExtendRealityLtd/Tilia.Locomotors.Teleporter.Unity#113]
### Environment
Tilia Locomotors Teleporter Unity version 2.2.0
Unity 2022.2.13

### Steps to reproduce
![Teleport](https://github.com/ExtendRealityLtd/Tilia.Locomotors.Teleporter.Unity/assets/46682105/0603784e-7a36-4591-8a79-c7dad0e595a6)

1) Place Locomotors.Teleporter.Instant on scene
2) Find PauseSnapping gameobject (child of Locomotors.Teleporter.Instant)
3) It is missing event

### Expected behavior
No missing event

### Current behavior
Has missing empty event

**Comment by thestonefox** [comment]
PR https://github.com/ExtendRealityLtd/Tilia.Locomotors.Teleporter.Unity/pull/114
