### ISSUE TITLE
Provide examples for Pointer Teleporter

### ISSUE THREAD

**Issue by studentutu** [ExtendRealityLtd/Tilia.Locomotors.Teleporter.Unity#39]
## Is your feature request related to a problem?

Lack of examples.

## Describe the solution you'd like

Add examples for  Pointer Teleporter with integrated Actions

## Additional context
Take prefab from TIlia.Prefabs
![image](https://user-images.githubusercontent.com/18601652/93882017-4ba5f100-fce8-11ea-936e-4369f96c95ff.png)

**Comment by thestonefox** [comment]
follow the project board for progress
https://github.com/orgs/ExtendRealityLtd/projects/6
