### ISSUE TITLE
Add a guide of How to prevent stepping up or skyrockets of the player with interactable objects

### ISSUE THREAD

**Issue by fight4dream** [ExtendRealityLtd/Tilia.Locomotors.Teleporter.Unity#94]
Epiczzor — Today at 1:30 PM
Hi all,
I've been working with VRTK4 and facing a small issue, My player rig 'steps up' or 'climbs' colliders (of interactable objects) when it gets too close to them. How can i disable or control this behavior ?

Epiczzor — Today at 2:41 PM
This is happening even if i move around in my VR space (without using teleporter) , if a grab an object and put it near my body, the camera steps up.

added a component type rule (to Teleporter Target Validity) with 'interactable facade' and negation rule, that didnt help

**Comment by thestonefox** [comment]
These videos cover things like this

https://www.youtube.com/watch?v=VdkbnsDNiQw

https://www.youtube.com/watch?v=2eKooviy6jw
